### ISSUE TITLE
v0.7.1.81 did not work on Windows 7 x64

### ISSUE THREAD

**Issue by ZURYB** [zeffy/wufuc#131]
Zeffy:
The link https://github.com/zeffy/wufuc/releases/latest shows wufuc v0.7.1.81 downloads. Can't find v0.8 with binaries.

I have a problem with Windows 7 x64 latest patches (from this week) installed. Copied existing disks to a new one and used a new motherboard.

The not supported message was still shown after installing and after rebooting (never worked).

I used the wufuc v0.7.1.81 zip file and installed from cmd as administrator.
 
Testing on a LAN, not Internet connected. Windows is not activated due to hardware changes. I cannot activate until I know everything works.

Logs:
[wufuclogs.zip](https://github.com/zeffy/wufuc/files/1608602/wufuclogs.zip)

sc queryex wuauserv output:
```SERVICE_NAME: wuauserv
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_PRESHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
        PID                : 2992
        FLAGS              :
```
What can I do to fix? Thanks!

**Comment by zeffy** [comment]
Looks like the same issue described in #103. It is fixed in the development code but I haven't released a new version yet because I'm still working out some other issues, but you can still work around it with v0.7.1.81.

v0.8 binaries were pulled because it had serious problems (BSODs, and other system instability) so I decided to scrap it entirely and start over.

Anyways, back to your issue. To fix this, open an elevated command line prompt by typing `cmd` into your start menu and right-clicking it and selecting Run as administrator, then enter this command:

```sc config wuauserv type= share```

Then press enter reboot your PC.

**Comment by ZURYB** [comment]
I have done that and rebooted. The service is now type: WIN32_SHARE_PROCESS. The "not supported" message still appears when attempting to use Windows Update, so it didn't work. 

Perhaps useful to know:
I copied the disk before rebooting after the January 4 updates on the old hardware, it finished installing during the boot at the new hardware (before use of wufuc). It shows those updates have been installed. They were installed manually.

**Comment by zeffy** [comment]
Hmm, yes I saw from your logs that wuaueng.dll resides on drive E:\. Is that the drive you have Windows installed on? It's possible having it on drive E:\ instead of C:\ could be causing problems. 

Can you upload your logs again now that you've reconfigured wuauserv to run in a shared process? Thanks

**Comment by ZURYB** [comment]
Yes Windows is on E:\Windows. C has an inaccessible directory called windows, but it does not have Windows files.

Logs: 
[wufuclogs2.zip](https://github.com/zeffy/wufuc/files/1608639/wufuclogs2.zip)

**Comment by zeffy** [comment]
Can you also run `sc queryex wuauserv` again and copy the output here? (Specifically the line that says PID).

**Comment by ZURYB** [comment]
```
sc queryex wuauserv

SERVICE_NAME: wuauserv
        TYPE               : 20  WIN32_SHARE_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_PRESHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
        PID                : 1356
        FLAGS              :
```

The PID changes at reboot or service restart.

**Comment by zeffy** [comment]
Weird, seems like it's still running in its own process regardless of service configuration. This may just be yet another edge case that v0.7 cannot handle very well. 

I believe the development version I'm currently working on should be able to handle it fine, but I don't have an ETA for it unfortunately. I've been taking my time to make sure everything is completely stable (I don't want a repeat of the v0.8 disaster).

I'll keep this issue open and notify you when a new version is available.

**Comment by ZURYB** [comment]
Thanks for you help and for this tool. I appreciate the work you put into it!
